name: webkitgtk-6-gnome-2404-sdk
base: core24
version: "2.45.3"
summary: Web content engine for GTK(SDK)
description: |
  SDK snap for Webkitgtk-6.0+, used with gnome-42-2204 and core22.
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  s390x:
parts:
  webkitgtk-6-gnome-2204-sdk:
    #source: https://webkitgtk.org/releases/webkitgtk-2.40.1.tar.xz
    source: https://github.com/WebKit/WebKit.git
    source-tag: "webkitgtk-2.45.3"
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DPORT=GTK
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET
      - -DCMAKE_INSTALL_LIBEXECDIR=lib/$CRAFT_ARCH_TRIPLET
      - -DCMAKE_SKIP_RPATH=ON
      - -DUSE_AVIF=ON
      - -DUSE_GTK4=ON
      - -DUSE_LIBBACKTRACE=OFF
      - -DUSE_JPEGXL=OFF
      - -DENABLE_JOURNALD_LOG=OFF
      - -DENABLE_DOCUMENTATION=OFF
      - -DENABLE_MINIBROWSER=ON
    build-packages:
      - bubblewrap
      - gettext
      - gperf
      - icu-devtools
      - libavif-dev
      - libcairo2-dev
      - libcurl4-gnutls-dev
      - libdav1d-dev
      - libenchant-2-dev
      - libepoxy-dev
      - libfreetype-dev
      - libgcrypt20-dev
      - libghc-text-icu-dev
      - libghc-text-icu-prof
      - libgav1-dev
      - libgirepository-1.0-dev
      - libglx-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgtk-4-dev
      - libharfbuzz-dev
      - libhyphen-dev
      - libicu-dev
      - liblcms2-dev
      - libmanette-0.2-dev
      - libnghttp2-dev
      - libopenjp2-7-dev
      - libopengl-dev
      - libpng-dev
      - libsoup-3.0-dev
      - libsecret-1-dev
      - libseccomp-dev
      - libsqlite3-dev
      - libtasn1-6-dev
      - libwebp-dev
      - libwoff-dev
      - libxcomposite-dev
      - libxdamage-dev
      - libxrender-dev
      - libxslt1-dev
      - libxt-dev
      - ruby-all-dev
      - unifdef
      - xdg-dbus-proxy
  deps:
    plugin: nil
    after: [webkitgtk-6-gnome-2204-sdk]
    override-prime: |
      craftctl default
      for PC in $(find . -path "*/pkgconfig/*.pc")
      do
         sed -i '1cprefix=/snap/webkitgtk-6-gnome-2404-sdk/current/usr' $PC
         sed -i 's#libdir=/usr/lib#libdir=${prefix}/lib#' $PC
      done
    stage-packages:
      - bubblewrap
      - gstreamer1.0-libav
      - libgstreamer-plugins-bad1.0-0
      - libaom3
      - libatomic1
      - libavif16
      - libdav1d7
      - libenchant-2-2
      - libgav1-1
      - libyuv0
    prime:
      - -etc
      - -lib
      - -usr/bin/fc*
      - -usr/bin/gencat
      - -usr/bin/i*
      - -usr/bin/r*
      - -usr/bin/s*
      - -usr/bin/u*
      - -usr/include
      - -usr/lib/aspell
      - -usr/lib/emacs*
      - -usr/lib/ispell
      - -usr/lib/sys*
      - -usr/lib/*/caca*
      - -usr/lib/*/enchant*
      - -usr/lib/*/gdk*
      - -usr/lib/*/gio
      - -usr/lib/*/gstreamer*
      - -usr/lib/*/libv4l*
      - -usr/lib/*/perl5
      - -usr/lib/*/*/libcrypt.pc
      - -usr/lib/*/*/libnsl.pc
      - -usr/lib/*/*/libtirpc.pc
      - -usr/lib/*/*/libxcrypt.pc
      - -usr/lib/*/*/zlib.pc
      - -usr/lib/*/pulseaudio
      - -usr/lib/*/crt*
      - -usr/lib/*/gcrt*
      - -usr/lib/*/grcrt*
      - -usr/lib/*/libaa*
      - -usr/lib/*/libanl*
      - -usr/lib/*/libasound*
      - -usr/lib/*/libaspell*
      - -usr/lib/*/libasyncns*
      - -usr/lib/*/libatomic*
      - -usr/lib/*/libavc139*
      - -usr/lib/*/libBroken*
      - -usr/lib/*/libc.a
      - -usr/lib/*/libc.so
      - -usr/lib/*/libca*
      - -usr/lib/*/libcd*
      - -usr/lib/*/libc_non*
      - -usr/lib/*/libcrypt*
      - -usr/lib/*/libdat*
      - -usr/lib/*/libdconf*
      - -usr/lib/*/libdeflate*
      - -usr/lib/*/libdl.a
      - -usr/lib/*/libdv*
      - -usr/lib/*/libdw*
      - -usr/lib/*/libenchant*
      - -usr/lib/*/libepoxy*
      - -usr/lib/*/libfontconf*
      - -usr/lib/*/libfribidi*
      - -usr/lib/*/libgdk*
      - -usr/lib/*/libgomp*
      - -usr/lib/*/libgpm*
      - -usr/lib/*/libgraphite*
      - -usr/lib/*/libgudev*
      - -usr/lib/*/libharf*
      - -usr/lib/*/libhuns*
      - -usr/lib/*/libicu*
      - -usr/lib/*/libiec*
      - -usr/lib/*/libjack*
      - -usr/lib/*/libjbig*
      - -usr/lib/*/libjpeg*
      - -usr/lib/*/libm.a
      - -usr/lib/*/libm.so
      - -usr/lib/*/libm-*
      - -usr/lib/*/libmcheck.a
      - -usr/lib/*/libmp*
      - -usr/lib/*/libmv*
      - -usr/lib/*/libnsl*
      - -usr/lib/*/libnss*
      - -usr/lib/*/libogg*
      - -usr/lib/*/libopenjp*
      - -usr/lib/*/libopus*
      - -usr/lib/*/liborc*
      - -usr/lib/*/libpango*
      - -usr/lib/*/libpixman*
      - -usr/lib/*/libproxy*
      - -usr/lib/*/libps*
      - -usr/lib/*/libpulse*
      - -usr/lib/*/libq*
      - -usr/lib/*/libraw*
      - -usr/lib/*/libre*
      - -usr/lib/*/librom*
      - -usr/lib/*/libsample*
      - -usr/lib/*/libshout*
      - -usr/lib/*/libslang*
      - -usr/lib/*/libsoup*
      - -usr/lib/*/libspeex*
      - -usr/lib/*/libtag*
      - -usr/lib/*/libth*
      - -usr/lib/*/libtiff*
      - -usr/lib/*/libtirp*
      - -usr/lib/*/libtw*
      - -usr/lib/*/libunwind*
      - -usr/lib/*/libva.so*
      - -usr/lib/*/libvis*
      - -usr/lib/*/libvo*
      - -usr/lib/*/libvpx*
      - -usr/lib/*/libwav*
      - -usr/lib/*/libwayland*
      - -usr/lib/*/libwebp*
      - -usr/lib/*/libX*
      - -usr/lib/*/libxcb*
      - -usr/lib/*/libxkb*
      - -usr/lib/*/libxml*
      - -usr/lib/*/libz.a
      - -usr/lib/*/libz.so
      - -usr/lib/*/*crt*
      - -usr/libexec
      - -usr/sbin
      - -usr/share
      - -usr/lib/x86_64-linux-gnu/libgstallocators-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstallocators-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstfft-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstfft-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstriff-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstriff-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstrtp-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstrtp-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstrtsp-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstrtsp-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstsdp-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstsdp-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgsttag-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgsttag-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0.2001.0
      - -usr/share/doc/libgstreamer-plugins-base1.0-0/changelog.Debian.gz
      - -usr/share/doc/libgstreamer-plugins-base1.0-0/copyright
      - -usr/share/gst-plugins-base/1.0/license-translations.dict
      - -usr/lib/x86_64-linux-gnu/libdrm.so.2
      - -usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
      - -usr/share/libdrm/amdgpu.ids
      - -usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcoreelements.so
      - -usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcoretracers.so
      - -usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
      - -usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-ptp-helper
      - -usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstcheck-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstcheck-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstcontroller-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstcontroller-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstnet-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstnet-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.2001.0
      - -usr/lib/x86_64-linux-gnu/glib-2.0/gio-launch-desktop
      - -usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules
      - -usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas
      - -usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.1
      - -usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
      - -usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.1
      - -usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.7200.1
      - -usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.1
      - -usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
      - -usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.7200.1
      - -usr/share/doc
      - -usr/share/glib-2.0/clean-up-unmanaged-libraries
      - -usr/share/lintian
