name: webkitgtk-6-gnome-2204-sdk # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Web content engine for GTK(SDK) # 79 char long summary
description: |
  SDK snap for Webkitgtk-6.0+, used with gnome-42-2204 and core22.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  webkitgtk-6-gnome-2204-sdk:
    #source: https://webkitgtk.org/releases/webkitgtk-2.40.1.tar.xz
    source: https://github.com/WebKit/WebKit.git
    source-tag: webkitgtk-2.40.1
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DPORT=GTK
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET
      - -DCMAKE_INSTALL_LIBEXECDIR=lib/$CRAFT_ARCH_TRIPLET
      - -DCMAKE_SKIP_RPATH=ON
      - -DUSE_AVIF=ON
      - -DUSE_GTK4=ON
      - -DENABLE_JOURNALD_LOG=OFF
      - -DENABLE_DOCUMENTATION=OFF
      - -DENABLE_MINIBROWSER=ON
    build-packages:
      - bubblewrap
      - gettext
      - gperf
      - icu-devtools
      - libavif-dev
      - libcairo2-dev
      - libcurl4-gnutls-dev
      - libdav1d-dev
      - libenchant-2-dev
      - libepoxy-dev
      - libfreetype-dev
      - libgcrypt20-dev
      - libghc-text-icu-dev
      - libghc-text-icu-prof
      - libgav1-dev
      - libglx-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgtk-4-dev
      - libharfbuzz-dev
      - libhyphen-dev
      - libicu-dev
      - libicu-le-hb-dev
      - liblcms2-dev
      - libmanette-0.2-dev
      - libnghttp2-dev
      - libopenjp2-7-dev
      - libopengl-dev
      - libpng-dev
      - libsoup-3.0-dev
      - libsecret-1-dev
      - libseccomp-dev
      - libsqlite3-dev
      - libtasn1-6-dev
      - libwebp-dev
      - libwpe-1.0-dev
      - libwpebackend-fdo-1.0-dev
      - libwoff-dev
      - libxcomposite-dev
      - libxdamage-dev
      - libxrender-dev
      - libxslt1-dev
      - libxt-dev
      - ruby-all-dev
      - unifdef
      - xdg-dbus-proxy
      
  deps:
    plugin: nil
    after: [webkitgtk-6-gnome-2204-sdk]
    override-prime: |
      craftctl default
      for PC in $(find . -path "*/pkgconfig/*.pc")
      do
         sed -i '1cprefix=/snap/webkitgtk-6-gnome-2204-sdk/current/usr' $PC
         sed -i 's#libdir=/usr/lib#libdir=${exec_prefix}/lib#' $PC
      done   
    stage-packages:
      - bubblewrap
      - gstreamer1.0-libav
      - libabsl20210324
      - libaom3
      - libatomic1
      - libavif13
      - libdav1d5
      - libenchant-2-2
      - libgav1-0
      - libwpe-1.0-1
      - libwpebackend-fdo-1.0-1
      - libyuv0
    prime:
      - -etc
      - -lib
      - -usr/bin/fc*
      - -usr/bin/gencat
      - -usr/bin/i*
      - -usr/bin/r*
      - -usr/bin/s*
      - -usr/bin/u*
      - -usr/include/arpa
      - -usr/include/asm-generic
      - -usr/include/drm
      - -usr/include/elfutils
      - -usr/include/finclude
      - -usr/include/linux
      - -usr/include/misc
      - -usr/include/mtd
      - -usr/include/net
      - -usr/include/netash
      - -usr/include/netatalk
      - -usr/include/netax25
      - -usr/include/neteconet
      - -usr/include/netinet
      - -usr/include/netipx
      - -usr/include/netiucv
      - -usr/include/netpacket
      - -usr/include/netrom
      - -usr/include/netrose
      - -usr/include/nfs
      - -usr/include/protocols
      - -usr/include/rdma
      - -usr/include/rpc
      - -usr/include/rpcsvc
      - -usr/include/scsi
      - -usr/include/sound
      - -usr/include/tirpc
      - -usr/include/video
      - -usr/include/x86_64-linux-gnu
      - -usr/include/xen
      - -usr/include/aio.h
      - -usr/include/aliases.h
      - -usr/include/alloca.h
      - -usr/include/ar.h
      - -usr/include/argp.h
      - -usr/include/argz.h
      - -usr/include/assert.h
      - -usr/include/byteswap.h
      - -usr/include/complex.h
      - -usr/include/cpio.h
      - -usr/include/crypt.h
      - -usr/include/ctype.h
      - -usr/include/dirent.h
      - -usr/include/dlfcn.h
      - -usr/include/elf.h
      - -usr/include/endian.h
      - -usr/include/envz.h
      - -usr/include/err.h
      - -usr/include/errno.h
      - -usr/include/error.h
      - -usr/include/execinfo.h
      - -usr/include/fcntl.h
      - -usr/include/features.h
      - -usr/include/features-time64.h
      - -usr/include/fenv.h
      - -usr/include/fmtmsg.h
      - -usr/include/fnmatch.h
      - -usr/include/fstab.h
      - -usr/include/fts.h
      - -usr/include/ftw.h
      - -usr/include/gconv.h
      - -usr/include/gelf.h
      - -usr/include/getopt.h
      - -usr/include/glob.h
      - -usr/include/gnu-versions.h
      - -usr/include/grp.h
      - -usr/include/gshadow.h
      - -usr/include/iconv.h
      - -usr/include/ifaddrs.h
      - -usr/include/inttypes.h
      - -usr/include/langinfo.h
      - -usr/include/lastlog.h
      - -usr/include/libelf.h
      - -usr/include/libgen.h
      - -usr/include/libintl.h
      - -usr/include/limits.h
      - -usr/include/link.h
      - -usr/include/locale.h
      - -usr/include/malloc.h
      - -usr/include/math.h
      - -usr/include/mcheck.h
      - -usr/include/memory.h
      - -usr/include/mntent.h
      - -usr/include/monetary.h
      - -usr/include/mqueue.h
      - -usr/include/netdb.h
      - -usr/include/nlist.h
      - -usr/include/nl_types.h
      - -usr/include/nss.h
      - -usr/include/obstack.h
      - -usr/include/paths.h
      - -usr/include/poll.h
      - -usr/include/printf.h
      - -usr/include/proc_service.h
      - -usr/include/pthread.h
      - -usr/include/pty.h
      - -usr/include/pwd.h
      - -usr/include/re_comp.h
      - -usr/include/regex.h
      - -usr/include/regexp.h
      - -usr/include/resolv.h
      - -usr/include/sched.h
      - -usr/include/search.h
      - -usr/include/semaphore.h
      - -usr/include/setjmp.h
      - -usr/include/sgtty.h
      - -usr/include/shadow.h
      - -usr/include/signal.h
      - -usr/include/stdio.h
      - -usr/include/stdlib.h
      - -usr/include/strings.h
      - -usr/include/string.h
      - -usr/include/stropts.h
      - -usr/include/sysctl.h
      - -usr/include/syslog.h
      - -usr/include/tar.h
      - -usr/include/termios.h
      - -usr/include/time.h
      - -usr/include/timers.h
      - -usr/include/ttyent.h
      - -usr/include/ulimit.h
      - -usr/include/unistd.h
      - -usr/include/utime.h
      - -usr/include/utmp.h
      - -usr/include/values.h
      - -usr/include/wordexp.h
      - -usr/include/xattr.h
      - -usr/include/zconf.h
      - -usr/include/zlib.h
      - -usr/include/zmq.h
      - -usr/lib/aspell
      - -usr/lib/emacs*
      - -usr/lib/ispell
      - -usr/lib/sys*
      - -usr/lib/*/caca*
      - -usr/lib/*/enchant*
      - -usr/lib/*/gdk*
      - -usr/lib/*/gio
      - -usr/lib/*/gstreamer*
      - -usr/lib/*/libv4l*
      - -usr/lib/*/perl5
      - -usr/lib/*/*/libcrypt.pc
      - -usr/lib/*/*/libnsl.pc
      - -usr/lib/*/*/libtirpc.pc
      - -usr/lib/*/*/libxcrypt.pc
      - -usr/lib/*/*/zlib.pc
      - -usr/lib/*/pulseaudio
      - -usr/lib/*/crt*
      - -usr/lib/*/gcrt*
      - -usr/lib/*/grcrt*
      - -usr/lib/*/libaa*
      - -usr/lib/*/libanl*
      - -usr/lib/*/libasound*
      - -usr/lib/*/libaspell*
      - -usr/lib/*/libasyncns*
      - -usr/lib/*/libatomic*
      - -usr/lib/*/libavc139*
      - -usr/lib/*/libBroken*
      - -usr/lib/*/libc.a
      - -usr/lib/*/libc.so
      - -usr/lib/*/libca*
      - -usr/lib/*/libcd*
      - -usr/lib/*/libc_non*
      - -usr/lib/*/libcrypt*
      - -usr/lib/*/libdat*
      - -usr/lib/*/libdconf*
      - -usr/lib/*/libdeflate*
      - -usr/lib/*/libdl.a
      - -usr/lib/*/libdv*
      - -usr/lib/*/libdw*
      - -usr/lib/*/libenchant*
      - -usr/lib/*/libepoxy*
      - -usr/lib/*/libfontconf*
      - -usr/lib/*/libfribidi*
      - -usr/lib/*/libgdk*
      - -usr/lib/*/libgomp*
      - -usr/lib/*/libgpm*
      - -usr/lib/*/libgraphite*
      - -usr/lib/*/libgst*
      - -usr/lib/*/libgudev*
      - -usr/lib/*/libharf*
      - -usr/lib/*/libhuns*
      - -usr/lib/*/libicu*
      - -usr/lib/*/libiec*
      - -usr/lib/*/libjack*
      - -usr/lib/*/libjbig*
      - -usr/lib/*/libjpeg*
      - -usr/lib/*/libm.a
      - -usr/lib/*/libm.so
      - -usr/lib/*/libm-*
      - -usr/lib/*/libmcheck.a
      - -usr/lib/*/libmp*
      - -usr/lib/*/libmv*
      - -usr/lib/*/libnsl*
      - -usr/lib/*/libnss*
      - -usr/lib/*/libogg*
      - -usr/lib/*/libopenjp*
      - -usr/lib/*/libopus*
      - -usr/lib/*/liborc*
      - -usr/lib/*/libpango*
      - -usr/lib/*/libpixman*
      - -usr/lib/*/libproxy*
      - -usr/lib/*/libps*
      - -usr/lib/*/libpulse*
      - -usr/lib/*/libq*
      - -usr/lib/*/libraw*
      - -usr/lib/*/libre*
      - -usr/lib/*/librom*
      - -usr/lib/*/libsample*
      - -usr/lib/*/libshout*
      - -usr/lib/*/libslang*
      - -usr/lib/*/libsoup*
      - -usr/lib/*/libspeex*
      - -usr/lib/*/libtag*
      - -usr/lib/*/libth*
      - -usr/lib/*/libtiff*
      - -usr/lib/*/libtirp*
      - -usr/lib/*/libtw*
      - -usr/lib/*/libunwind*
      - -usr/lib/*/libvis*
      - -usr/lib/*/libvo*
      - -usr/lib/*/libvpx*
      - -usr/lib/*/libwav*
      - -usr/lib/*/libwayland*
      - -usr/lib/*/libwebp*
      - -usr/lib/*/libX*
      - -usr/lib/*/libxcb*
      - -usr/lib/*/libxkb*
      - -usr/lib/*/libxml*
      - -usr/lib/*/libz.a
      - -usr/lib/*/libz.so
      - -usr/lib/*/*crt*
      - -usr/libexec
      - -usr/sbin
      - -usr/share

