name: webkitgtk-6-gnome-2204 # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Web content engine for GTK # 79 char long summary
description: |
  Content snap for Webkitgtk-6.0+

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  webkitgtk-6-gnome-2204:
    interface: content
    read:
      - /

parts:
  webkitgtk:
    plugin: nil
    stage-snaps: [ webkitgtk-6-gnome-2204-sdk/latest/edge ]
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -meta*
      - -snap*
