name: Update Snap

on:
  # Runs at 10:00 UTC every day
  schedule:
    - cron: "0 10 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-sdk:
    name: Sync version of the SDK snap with upstream
    environment: "2404 Branch"
    runs-on: ubuntu-latest
    steps:
      - name: Sync version with upstream
        uses: snapcrafters/ci/sync-version@main
        id: sync-sdk-version
        with:
          token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          branch: "2404"
          snapcraft-project-root: "webkitgtk-6-gnome-2404-sdk"
          update-script: |
            webkitgtk_version=$(git ls-remote --refs --sort='v:refname' --tags 'https://github.com/WebKit/WebKit.git' "webkitgtk-*" | awk -F'/' '{print $NF}' | grep -E 'webkitgtk-[0-9]+(\.[0-9]+)*\.[0-9]$' | sort -V | tail -n 1 | sed 's/^webkitgtk-//')
            yq -i ".version=\"$webkitgtk_version\"" webkitgtk-6-gnome-2404-sdk/snapcraft.yaml

  sync-content-version:
    needs: sync-sdk
    name: Sync version of the content snap with upstream
    environment: "2404 Branch"
    runs-on: ubuntu-latest
    steps:
      - name: Sync version with upstream
        uses: snapcrafters/ci/sync-version@main
        with:
          token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          branch: "2404"
          snapcraft-project-root: "webkitgtk-6-gnome-2404"
          update-script: |
            webkitgtk_version=$(git ls-remote --refs --sort='v:refname' --tags 'https://github.com/WebKit/WebKit.git' "webkitgtk-*" | awk -F'/' '{print $NF}' | grep -E 'webkitgtk-[0-9]+(\.[0-9]+)*\.[0-9]$' | sort -V | tail -n 1 | sed 's/^webkitgtk-//') 
            yq -i ".version=\"$webkitgtk_version\"" webkitgtk-6-gnome-2404/snapcraft.yaml
